/* eslint-disable import/no-extraneous-dependencies */
/* eslint-disable global-require */
const colors = require("tailwindcss/colors");
const defaultTheme = require("tailwindcss/defaultTheme");
// const radix = require("@radix-ui/colors");
module.exports = {
  presets: [require("@samrobbins/typography")],
  darkMode: "class",
  mode: "jit",
  purge: [
    "./components/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./lib/snippet.js",
  ],
  theme: {
    extend: {
      colors: {
        gray: colors.coolGray,
        teal: colors.teal,
        orange: colors.orange,
        fuchsia: colors.fuchsia,
        cyan: colors.cyan,
        lime: colors.lime,
        sky: colors.sky,
        rose: colors.rose,
        emerald: colors.emerald,
        npm: "#CB3837",
        gmail: "#EA4335",
        twitter: "#1DA1F2",
        linkedin: "#0A66C2",
        "nord6.1": "#f8f9fb",
        link: "#0077aa",
        darkLink: "#96d0ff",
        test: "var(--primary)",
        radix: {
          sky1: "var(--sky1)",
          sky2: "var(--sky2)",
          sky3: "var(--sky3)",
          sky4: "var(--sky4)",
          sky5: "var(--sky5)",
          sky6: "var(--sky6)",
          sky7: "var(--sky7)",
          sky8: "var(--sky8)",
          sky9: "var(--sky9)",
          sky10: "var(--sky10)",
          sky11: "var(--sky11)",
          sky12: "var(--sky12)",
          gray1: "var(--gray1)",
          gray2: "var(--gray2)",
          gray3: "var(--gray3)",
          gray4: "var(--gray4)",
          gray5: "var(--gray5)",
          gray6: "var(--gray6)",
          gray7: "var(--gray7)",
          gray8: "var(--gray8)",
          gray9: "var(--gray9)",
          gray10: "var(--gray10)",
          gray11: "var(--gray11)",
          gray12: "var(--gray12)",
          slate1: "var(--slate1)",
          slate2: "var(--slate2)",
          slate3: "var(--slate3)",
          slate4: "var(--slate4)",
          slate5: "var(--slate5)",
          slate6: "var(--slate6)",
          slate7: "var(--slate7)",
          slate8: "var(--slate8)",
          slate9: "var(--slate9)",
          slate10: "var(--slate10)",
          slate11: "var(--slate11)",
          slate12: "var(--slate12)",
        },
      },
      zIndex: {
        "-10": "-10",
        "-20": "-20",
      },
      maxWidth: {
        "85ch": "85ch",
        "65ch": "65ch",
        prose: "85ch",
      },
      flex: {
        "1/4": "1 0 25%",
        "1/2": "1 0 50%",
      },
      fontFamily: {
        latex: ["Latin Modern"],
        sans: ["Inter var", ...defaultTheme.fontFamily.sans],
        serif: ["Newsreader", ...defaultTheme.fontFamily.serif],
      },
      height: {
        18: "4.5rem",
      },
    },
  },
  variants: {
    extend: {
      display: ["hover"],
      backgroundColor: ["active"],
      fontWeight: ["active", "focus"],
      boxShadow: ["group-focus"],
      outline: ["group-focus"],
      ringColor: ["hover", "active"],
      outlinePlugin: ["hover", "focus", "group-focus"],
    },
  },
  plugins: [require("tailwind-outline-plugin"), require("tailwind-nord")],
};
